---
- name: Custom Play with Python
  hosts: localhost

  vars:
    custom_list:
      - 'apple'
      - 'funny'
      - 'Hot cheetoes'
      - 'www.google.com'
      - '7200'
      - '85339'
      - 'San Diego'

  tasks:
  - name: Just numbers
    debug:
      msg: "{{custom_list | reject('letters') }}"
